http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    security-headers:
      headers:
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer"
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
