http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    security-headers:
      headers:
        contentTypeNosniff: true
        browserXssFilter: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        # Strips HTTP_REFERER, among other things. Breaks some e-commerce using
        # wp_get_referer() and $_SERVER['http_referer'].
        # referrerPolicy: "no-referrer"
