global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: traefik
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
  - job_name: alertmanager
    scheme: http
    static_configs:
      - targets: [ 'alertmanager:9093' ]
